"""
state.py — LangGraph State Definition
======================================
Defines the shared AgentState schema used by all nodes in the LangGraph loop.
"""

from typing import Any, Dict, List, TypedDict


class AgentState(TypedDict):
    """
    Shared state for the Scientific Reasoning Core workflow.
    """
    # 1. Input anomalies & parameters
    anomalies: Dict[str, Any]      # Active anomalies/readings (e.g., Gas, Vibration, Env, Navigation)
    segment_id: str                # Target tunnel segment ID (e.g., "TUNNEL_A3")
    
    # 2. Retrieved context
    ekg_history: str               # Text summary of historical events/anomalies from the EKG
    rag_context: str               # Text safety guidelines retrieved from FAISS database
    
    # 3. Reasoning outputs
    hypothesis: str                # Root cause/anomaly explanation generated by the LLM
    suggestions: List[str]         # Actionable advice and mitigation steps
    
    # 4. Status and logs
    trace: List[str]               # Step-by-step logs of node execution status
    status: str                    # Final resolution status ("SUCCESS", "WARNING", or "FAILED")
